2024-09-12 10:36:07 [   ERROR] [test_03_logging] test_case03 xfail (test_03_logging.py:33)
2024-09-12 10:36:07 [   ERROR] [test_03_logging] func1 ValueError (test_03_logging.py:25)
